### ISSUE TITLE
coc-angular fails to load

### ISSUE THREAD

**Issue by royyhlee** [iamcco/coc-angular#2]
I'm having trouble trying to get this to work, this is what I have in `CocInfo`:

```
## Output channel: angularls
pkg/prelude/bootstrap.js:1178
      throw error;
      ^

Error: Cannot find module '@angular/compiler-cli/src/language_services'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/module.js:11:18)
    at /home/royyhlee/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:21:31
    at Object.defineProperty.value (/home/royyhlee/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:10:17)
    at Object.<anonymous> (/home/royyhlee/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:16:3)
    at Module._compile (module.js:633:30)
[Info  - 12:11:05] Connection to server got closed. Server will restart.

```

**Comment by iamcco** [comment]
fix, update and have a try.

**Comment by royyhlee** [comment]
Sorry for the late response.

I ran the update but I'm still having the same issue :( 

```
## Output channel: angularls
pkg/prelude/bootstrap.js:1178
      throw error;
      ^

Error: Cannot find module '@angular/compiler-cli/src/language_services'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/module.js:11:18)
    at /home/royyhlee/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:21:31
    at Object.defineProperty.value (/home/royyhlee/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:10:17)
    at Object.<anonymous> (/home/royyhlee/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:16:3)
    at Module._compile (module.js:633:30)
[Info  - 11:13:49] Connection to server got closed. Server will restart.

```

**Comment by iamcco** [comment]
open this directory to see if `@angular/compiler-cli` exists:

![image](https://user-images.githubusercontent.com/5492542/55371758-f5605380-5531-11e9-98f4-f894240d4629.png)

**Comment by royyhlee** [comment]
This is what I have after fresh install of coc-angular:
```
$ ls ~/.config/coc/extensions/node_modules/@angular
compiler  core  language-service
```

**Comment by iamcco** [comment]
I have include the source code, should be fix after update. `CocInstall coc-angular`

**Comment by royyhlee** [comment]
Works like a charm! I'm loving the plugin, thank you :)
